/* prestage - drop intermediate insert table */ 
DROP TABLE if exists dw_prestage.vendors_insert;

/* prestage - create intermediate insert table*/ 
CREATE TABLE dw_prestage.vendors_insert 
AS
SELECT *
FROM dw_prestage.vendors
WHERE EXISTS (SELECT 1
              FROM (SELECT vendor_id
                    FROM (SELECT vendor_id
                          FROM dw_prestage.vendors
                          MINUS
                          SELECT vendor_id
                          FROM dw_stage.vendors)) a
              WHERE dw_prestage.vendors.vendor_id = a.vendor_id);

/* prestage - drop intermediate update table*/ 
DROP TABLE if exists dw_prestage.vendors_update;

/* prestage - create intermediate update table*/ 
CREATE TABLE dw_prestage.vendors_update 
AS
SELECT decode(SUM(ch_type),
             3,2,
             SUM(ch_type)
       )  ch_type,
       vendor_id
FROM (SELECT vendor_id,
             CH_TYPE
      FROM (SELECT vendor_id,
                   BILLADDRESS,
                   SHIPADDRESS,
                   ACCOUNTNUMBER,
                   LINE1,
                   LINE2,
                   LINE3,
                   ZIPCODE,
                   CITY,
                   STATE,
                   COUNTRY,
                   COMPANYNAME,
                   CURRENCY_NAME,
                   CURRENCY_ID,
                   '2' CH_TYPE
            FROM dw_prestage.vendors
            MINUS
            SELECT vendor_id,
                   BILLADDRESS,
                   SHIPADDRESS,
                   ACCOUNTNUMBER,
                   LINE1,
                   LINE2,
                   LINE3,
                   ZIPCODE,
                   CITY,
                   STATE,
                   COUNTRY,
                   COMPANYNAME,
                   CURRENCY_NAME,
                   CURRENCY_ID,
                   '2' CH_TYPE
            FROM dw_stage.vendors)
      UNION ALL
      SELECT vendor_id,
             CH_TYPE
      FROM (SELECT vendor_id,
                   VENDOR_EXTID,
                   NAME,
                   EMAIL,
                   FULL_NAME,
                   EFT_BILL_PAYMENT,
                   IS1099ELIGIBLE,
                   ISINACTIVE,
                   IS_PERSON,
                   LINE_OF_BUSINESS,
                   LINE_OF_BUSINESS_ID,
                   SUBSIDIARY_NAME,
                   SUBSIDIARY,
                   VENDOR_TYPE,
                   '1' CH_TYPE
            FROM dw_prestage.vendors
            MINUS
            SELECT vendor_id,
                   VENDOR_EXTID,
                   NAME,
                   EMAIL,
                   FULL_NAME,
                   EFT_BILL_PAYMENT,
                   IS1099ELIGIBLE,
                   ISINACTIVE,
                   IS_PERSON,
                   LINE_OF_BUSINESS,
                   LINE_OF_BUSINESS_ID,
                   SUBSIDIARY_NAME,
                   SUBSIDIARY,
                   VENDOR_TYPE,
                   '1' CH_TYPE
            FROM dw_stage.vendors)) a
WHERE NOT EXISTS (SELECT 1
                  FROM dw_prestage.vendors_insert
                  WHERE dw_prestage.vendors_insert.vendor_id = a.vendor_id)
GROUP BY vendor_id;

/* prestage - drop intermediate delete table*/ 
DROP TABLE if exists dw_prestage.vendors_delete;

/* prestage - create intermediate delete table*/ 
CREATE TABLE dw_prestage.vendors_delete 
AS
SELECT *
FROM dw_stage.vendors
WHERE EXISTS (SELECT 1
              FROM (SELECT vendor_id
                    FROM (SELECT vendor_id
                          FROM dw_stage.vendors
                          MINUS
                          SELECT vendor_id
                          FROM dw_prestage.vendors)) a
              WHERE dw_stage.vendors.vendor_id = a.vendor_id);

/* prestage-> stage*/ 
SELECT 'no of prestage vendor records identified to inserted -->' ||count(1)
FROM dw_prestage.vendors_insert;

/* prestage-> stage*/ 
SELECT 'no of prestage vendor records identified to updated -->' ||count(1)
FROM dw_prestage.vendors_update;

/* prestage-> stage*/ 
SELECT 'no of prestage vendor records identified to deleted -->' ||count(1)
FROM dw_prestage.vendors_delete;

/* stage -> delete from stage records to be updated */ 
DELETE
FROM dw_stage.vendors USING dw_prestage.vendors_update
WHERE dw_stage.vendors.vendor_id = dw_prestage.vendors_update.vendor_id;

/* stage -> delete from stage records which have been deleted */ 
DELETE
FROM dw_stage.vendors USING dw_prestage.vendors_delete
WHERE dw_stage.vendors.vendor_id = dw_prestage.vendors_delete.vendor_id;

/* stage -> insert into stage records which have been created */ 
INSERT INTO dw_stage.vendors
(
  ABCD_MARKER_ID,
  ACCOUNTNUMBER,
  ACTUAL_COST,
  ALTEMAIL,
  ALTERNATE_CUSTOMER_EMAIL,
  ALTERNATE_CUSTOMER_EMAIL1,
  ALTERNATE_CUSTOMER_EMAIL2,
  ALTPHONE,
  APPLY_FREIGHT,
  BACKORDERS_ALLOWED,
  BACK_ORDER_SPLIT,
  BILLADDRESS,
  BILLING_CLASS_ID,
  BOOK_FAIRS_CONSULTANT_ID,
  BOOK_FAIR_ABCD_MARKER,
  BOOK_FAIR_SIZE_ID,
  BRN,
  BUSINESS_STYLE_ID,
  CARRIER_ADDRESS,
  CARRIER_LABEL_ID,
  CITY,
  COMMENTS,
  COMPANYNAME,
  COST_EXPIRED,
  COUNTRY,
  CREATE_DATE,
  CREDITLIMIT,
  CTC,
  CURRENCY_ID,
  CURRENCY_NAME,
  CUSTOMER_ID,
  DATE_CUSTOMER_STATEMENT_SENT,
  DATE_LAST_MODIFIED,
  DECILE_ID,
  DEFAULT_DISCOUNT_ID,
  DEFAULT_DISCOUNT_RATE,
  DEFAULT_WT_CODE_ID,
  DELIVERY_INSTRUCTION,
  DIRECT_DEBIT,
  EFT_BILL_PAYMENT,
  EFT_CUSTOMER_REFUND_PAYMENT,
  EFT_FILE_FORMAT_ID,
  ELIGIBLE_FOR_APPROVAL,
  EMAIL,
  EMAIL_ADDRESS,
  EMAIL_ADDRESS_FOR_PAYMENT_NOT,
  EMAIL_ADDRESS_FOR_PAYMENT_NO_0,
  EMAIL_FOR_CUSTOMER_STATEMENT,
  EMAIL_FOR_CUSTOMER_STATEMENT_,
  EMAIL_FOR_CUSTOMER_STATEMENT_0,
  EMAIL_FOR_CUSTOMER_STATEMENT_1,
  EMPLOYEE_ID,
  EXPENSE_ACCOUNT_ID,
  FAIR_SIZE,
  FAIR_TYPE_ID,
  FAX,
  FINANCIAL,
  FORWARDERS_ADDRESS_ID,
  FORWARDER_ADDRESS,
  FREIGHT_ESTIMATE_METHOD_ID,
  FREIGHT_RATE,
  FULL_NAME,
  HOME_PHONE,
  INCOTERM,
  IS1099ELIGIBLE,
  ISEMAILHTML,
  ISEMAILPDF,
  ISINACTIVE,
  IS_PERSON,
  LABOR_COST,
  LAST_MODIFIED_DATE,
  LAST_SALES_ACTIVITY,
  LEGACY_CUSTOMER_IDCUSTOM,
  LINE1,
  LINE2,
  LINE3,
  LINE_OF_BUSINESS_ID,
  LINE_OF_BUSINESS,
  LOGINACCESS,
  LSA_LINK,
  LSA_LINK_NAME,
  MOBILE_PHONE,
  MOE_ID,
  NAME,
  NO_OF_CHILDREN_ENROLLED,
  OLD_CUSTOMER_CODE,
  OLD_PARENT_CODE,
  OPENBALANCE,
  OPENBALANCE_FOREIGN,
  OPENING_BALANCE,
  PAYABLES_ACCOUNT_ID,
  PAYMENT_TERMS_ID,
  PHILHEALTH,
  PHONE,
  PRICE_GROUP_ID,
  PRINTONCHECKAS,
  PROJECT_SCOPE_STATEMENT,
  PROVIDENT_FUND_NUMBER,
  PURCHASEORDERAMOUNT,
  PURCHASEORDERQUANTITY,
  PURCHASEORDERQUANTITYDIFF,
  RECEIPTAMOUNT,
  RECEIPTQUANTITY,
  RECEIPTQUANTITYDIFF,
  REGION_ID,
  REWARDS_BAND_ID,
  REWARD_EARNER_ID,
  ROUTE_CODE_ID,
  SALES_TERRITORYDO_NOT_USE_ID,
  SCHEMAI1L_FOR_INVOICE,
  SCHEMAIL_FOR_INVOICE,
  SCHOLASTIC_SALES_TERRITORY_ID,
  SELLING_RIGHTS_ID,
  SHIPADDRESS,
  SHIPPING_PREFERENCE_ID,
  SNIPP_MEMBER_ID,
  SOR_DISCOUNT_ID,
  SOR_DURATION_FROM_DAYS,
  SOR_DURATION_TO_DAYS,
  SOR_TAG,
  SOR_THRESHOLD,
  SPONSOR,
  STAPLES,
  STATE,
  SUBSIDIARY,
  SUBSIDIARY_NAME,
  TAXIDNUM,
  TAX_CONTACT_FIRST_NAME,
  TAX_CONTACT_ID,
  TAX_CONTACT_LAST_NAME,
  TAX_CONTACT_MIDDLE_NAME,
  THIRD_PARTY,
  TIN,
  TOTAL_QUANTITY,
  TRANSACTIONS_NEED_APPROVAL,
  UEN,
  UK_OTC_CODE,
  UNBILLED_ORDERS,
  UNBILLED_ORDERS_FOREIGN,
  URL,
  US_OTC_CODE,
  VAT_REGISTRATION_NO,
  VENDOR_EXTID,
  VENDOR_ID,
  VENDOR_TYPE_ID,
  VENDOR_TYPE,
  ZIPCODE,
  ZONE_NUMBER_ID
)
SELECT ABCD_MARKER_ID,
       ACCOUNTNUMBER,
       ACTUAL_COST,
       ALTEMAIL,
       ALTERNATE_CUSTOMER_EMAIL,
       ALTERNATE_CUSTOMER_EMAIL1,
       ALTERNATE_CUSTOMER_EMAIL2,
       ALTPHONE,
       APPLY_FREIGHT,
       BACKORDERS_ALLOWED,
       BACK_ORDER_SPLIT,
       BILLADDRESS,
       BILLING_CLASS_ID,
       BOOK_FAIRS_CONSULTANT_ID,
       BOOK_FAIR_ABCD_MARKER,
       BOOK_FAIR_SIZE_ID,
       BRN,
       BUSINESS_STYLE_ID,
       CARRIER_ADDRESS,
       CARRIER_LABEL_ID,
       CITY,
       COMMENTS,
       COMPANYNAME,
       COST_EXPIRED,
       COUNTRY,
       CREATE_DATE,
       CREDITLIMIT,
       CTC,
       CURRENCY_ID,
       CURRENCY_NAME,
       CUSTOMER_ID,
       DATE_CUSTOMER_STATEMENT_SENT,
       DATE_LAST_MODIFIED,
       DECILE_ID,
       DEFAULT_DISCOUNT_ID,
       DEFAULT_DISCOUNT_RATE,
       DEFAULT_WT_CODE_ID,
       DELIVERY_INSTRUCTION,
       DIRECT_DEBIT,
       EFT_BILL_PAYMENT,
       EFT_CUSTOMER_REFUND_PAYMENT,
       EFT_FILE_FORMAT_ID,
       ELIGIBLE_FOR_APPROVAL,
       EMAIL,
       EMAIL_ADDRESS,
       EMAIL_ADDRESS_FOR_PAYMENT_NOT,
       EMAIL_ADDRESS_FOR_PAYMENT_NO_0,
       EMAIL_FOR_CUSTOMER_STATEMENT,
       EMAIL_FOR_CUSTOMER_STATEMENT_,
       EMAIL_FOR_CUSTOMER_STATEMENT_0,
       EMAIL_FOR_CUSTOMER_STATEMENT_1,
       EMPLOYEE_ID,
       EXPENSE_ACCOUNT_ID,
       FAIR_SIZE,
       FAIR_TYPE_ID,
       FAX,
       FINANCIAL,
       FORWARDERS_ADDRESS_ID,
       FORWARDER_ADDRESS,
       FREIGHT_ESTIMATE_METHOD_ID,
       FREIGHT_RATE,
       FULL_NAME,
       HOME_PHONE,
       INCOTERM,
       IS1099ELIGIBLE,
       ISEMAILHTML,
       ISEMAILPDF,
       ISINACTIVE,
       IS_PERSON,
       LABOR_COST,
       LAST_MODIFIED_DATE,
       LAST_SALES_ACTIVITY,
       LEGACY_CUSTOMER_IDCUSTOM,
       LINE1,
       LINE2,
       LINE3,
       LINE_OF_BUSINESS_ID,
       LINE_OF_BUSINESS,
       LOGINACCESS,
       LSA_LINK,
       LSA_LINK_NAME,
       MOBILE_PHONE,
       MOE_ID,
       NAME,
       NO_OF_CHILDREN_ENROLLED,
       OLD_CUSTOMER_CODE,
       OLD_PARENT_CODE,
       OPENBALANCE,
       OPENBALANCE_FOREIGN,
       OPENING_BALANCE,
       PAYABLES_ACCOUNT_ID,
       PAYMENT_TERMS_ID,
       PHILHEALTH,
       PHONE,
       PRICE_GROUP_ID,
       PRINTONCHECKAS,
       PROJECT_SCOPE_STATEMENT,
       PROVIDENT_FUND_NUMBER,
       PURCHASEORDERAMOUNT,
       PURCHASEORDERQUANTITY,
       PURCHASEORDERQUANTITYDIFF,
       RECEIPTAMOUNT,
       RECEIPTQUANTITY,
       RECEIPTQUANTITYDIFF,
       REGION_ID,
       REWARDS_BAND_ID,
       REWARD_EARNER_ID,
       ROUTE_CODE_ID,
       SALES_TERRITORYDO_NOT_USE_ID,
       SCHEMAI1L_FOR_INVOICE,
       SCHEMAIL_FOR_INVOICE,
       SCHOLASTIC_SALES_TERRITORY_ID,
       SELLING_RIGHTS_ID,
       SHIPADDRESS,
       SHIPPING_PREFERENCE_ID,
       SNIPP_MEMBER_ID,
       SOR_DISCOUNT_ID,
       SOR_DURATION_FROM_DAYS,
       SOR_DURATION_TO_DAYS,
       SOR_TAG,
       SOR_THRESHOLD,
       SPONSOR,
       STAPLES,
       STATE,
       SUBSIDIARY,
       SUBSIDIARY_NAME,
       TAXIDNUM,
       TAX_CONTACT_FIRST_NAME,
       TAX_CONTACT_ID,
       TAX_CONTACT_LAST_NAME,
       TAX_CONTACT_MIDDLE_NAME,
       THIRD_PARTY,
       TIN,
       TOTAL_QUANTITY,
       TRANSACTIONS_NEED_APPROVAL,
       UEN,
       UK_OTC_CODE,
       UNBILLED_ORDERS,
       UNBILLED_ORDERS_FOREIGN,
       URL,
       US_OTC_CODE,
       VAT_REGISTRATION_NO,
       VENDOR_EXTID,
       VENDOR_ID,
       VENDOR_TYPE_ID,
       VENDOR_TYPE,
       ZIPCODE,
       ZONE_NUMBER_ID
FROM dw_prestage.vendors_insert;

/* stage -> insert into stage records which have been created */ 
INSERT INTO dw_stage.vendors
(
  ABCD_MARKER_ID,
  ACCOUNTNUMBER,
  ACTUAL_COST,
  ALTEMAIL,
  ALTERNATE_CUSTOMER_EMAIL,
  ALTERNATE_CUSTOMER_EMAIL1,
  ALTERNATE_CUSTOMER_EMAIL2,
  ALTPHONE,
  APPLY_FREIGHT,
  BACKORDERS_ALLOWED,
  BACK_ORDER_SPLIT,
  BILLADDRESS,
  BILLING_CLASS_ID,
  BOOK_FAIRS_CONSULTANT_ID,
  BOOK_FAIR_ABCD_MARKER,
  BOOK_FAIR_SIZE_ID,
  BRN,
  BUSINESS_STYLE_ID,
  CARRIER_ADDRESS,
  CARRIER_LABEL_ID,
  CITY,
  COMMENTS,
  COMPANYNAME,
  COST_EXPIRED,
  COUNTRY,
  CREATE_DATE,
  CREDITLIMIT,
  CTC,
  CURRENCY_ID,
  CURRENCY_NAME,
  CUSTOMER_ID,
  DATE_CUSTOMER_STATEMENT_SENT,
  DATE_LAST_MODIFIED,
  DECILE_ID,
  DEFAULT_DISCOUNT_ID,
  DEFAULT_DISCOUNT_RATE,
  DEFAULT_WT_CODE_ID,
  DELIVERY_INSTRUCTION,
  DIRECT_DEBIT,
  EFT_BILL_PAYMENT,
  EFT_CUSTOMER_REFUND_PAYMENT,
  EFT_FILE_FORMAT_ID,
  ELIGIBLE_FOR_APPROVAL,
  EMAIL,
  EMAIL_ADDRESS,
  EMAIL_ADDRESS_FOR_PAYMENT_NOT,
  EMAIL_ADDRESS_FOR_PAYMENT_NO_0,
  EMAIL_FOR_CUSTOMER_STATEMENT,
  EMAIL_FOR_CUSTOMER_STATEMENT_,
  EMAIL_FOR_CUSTOMER_STATEMENT_0,
  EMAIL_FOR_CUSTOMER_STATEMENT_1,
  EMPLOYEE_ID,
  EXPENSE_ACCOUNT_ID,
  FAIR_SIZE,
  FAIR_TYPE_ID,
  FAX,
  FINANCIAL,
  FORWARDERS_ADDRESS_ID,
  FORWARDER_ADDRESS,
  FREIGHT_ESTIMATE_METHOD_ID,
  FREIGHT_RATE,
  FULL_NAME,
  HOME_PHONE,
  INCOTERM,
  IS1099ELIGIBLE,
  ISEMAILHTML,
  ISEMAILPDF,
  ISINACTIVE,
  IS_PERSON,
  LABOR_COST,
  LAST_MODIFIED_DATE,
  LAST_SALES_ACTIVITY,
  LEGACY_CUSTOMER_IDCUSTOM,
  LINE1,
  LINE2,
  LINE3,
  LINE_OF_BUSINESS_ID,
  LINE_OF_BUSINESS,
  LOGINACCESS,
  LSA_LINK,
  LSA_LINK_NAME,
  MOBILE_PHONE,
  MOE_ID,
  NAME,
  NO_OF_CHILDREN_ENROLLED,
  OLD_CUSTOMER_CODE,
  OLD_PARENT_CODE,
  OPENBALANCE,
  OPENBALANCE_FOREIGN,
  OPENING_BALANCE,
  PAYABLES_ACCOUNT_ID,
  PAYMENT_TERMS_ID,
  PHILHEALTH,
  PHONE,
  PRICE_GROUP_ID,
  PRINTONCHECKAS,
  PROJECT_SCOPE_STATEMENT,
  PROVIDENT_FUND_NUMBER,
  PURCHASEORDERAMOUNT,
  PURCHASEORDERQUANTITY,
  PURCHASEORDERQUANTITYDIFF,
  RECEIPTAMOUNT,
  RECEIPTQUANTITY,
  RECEIPTQUANTITYDIFF,
  REGION_ID,
  REWARDS_BAND_ID,
  REWARD_EARNER_ID,
  ROUTE_CODE_ID,
  SALES_TERRITORYDO_NOT_USE_ID,
  SCHEMAI1L_FOR_INVOICE,
  SCHEMAIL_FOR_INVOICE,
  SCHOLASTIC_SALES_TERRITORY_ID,
  SELLING_RIGHTS_ID,
  SHIPADDRESS,
  SHIPPING_PREFERENCE_ID,
  SNIPP_MEMBER_ID,
  SOR_DISCOUNT_ID,
  SOR_DURATION_FROM_DAYS,
  SOR_DURATION_TO_DAYS,
  SOR_TAG,
  SOR_THRESHOLD,
  SPONSOR,
  STAPLES,
  STATE,
  SUBSIDIARY,
  SUBSIDIARY_NAME,
  TAXIDNUM,
  TAX_CONTACT_FIRST_NAME,
  TAX_CONTACT_ID,
  TAX_CONTACT_LAST_NAME,
  TAX_CONTACT_MIDDLE_NAME,
  THIRD_PARTY,
  TIN,
  TOTAL_QUANTITY,
  TRANSACTIONS_NEED_APPROVAL,
  UEN,
  UK_OTC_CODE,
  UNBILLED_ORDERS,
  UNBILLED_ORDERS_FOREIGN,
  URL,
  US_OTC_CODE,
  VAT_REGISTRATION_NO,
  VENDOR_EXTID,
  VENDOR_ID,
  VENDOR_TYPE_ID,
  VENDOR_TYPE,
  ZIPCODE,
  ZONE_NUMBER_ID
)
SELECT ABCD_MARKER_ID,
       ACCOUNTNUMBER,
       ACTUAL_COST,
       ALTEMAIL,
       ALTERNATE_CUSTOMER_EMAIL,
       ALTERNATE_CUSTOMER_EMAIL1,
       ALTERNATE_CUSTOMER_EMAIL2,
       ALTPHONE,
       APPLY_FREIGHT,
       BACKORDERS_ALLOWED,
       BACK_ORDER_SPLIT,
       BILLADDRESS,
       BILLING_CLASS_ID,
       BOOK_FAIRS_CONSULTANT_ID,
       BOOK_FAIR_ABCD_MARKER,
       BOOK_FAIR_SIZE_ID,
       BRN,
       BUSINESS_STYLE_ID,
       CARRIER_ADDRESS,
       CARRIER_LABEL_ID,
       CITY,
       COMMENTS,
       COMPANYNAME,
       COST_EXPIRED,
       COUNTRY,
       CREATE_DATE,
       CREDITLIMIT,
       CTC,
       CURRENCY_ID,
       CURRENCY_NAME,
       CUSTOMER_ID,
       DATE_CUSTOMER_STATEMENT_SENT,
       DATE_LAST_MODIFIED,
       DECILE_ID,
       DEFAULT_DISCOUNT_ID,
       DEFAULT_DISCOUNT_RATE,
       DEFAULT_WT_CODE_ID,
       DELIVERY_INSTRUCTION,
       DIRECT_DEBIT,
       EFT_BILL_PAYMENT,
       EFT_CUSTOMER_REFUND_PAYMENT,
       EFT_FILE_FORMAT_ID,
       ELIGIBLE_FOR_APPROVAL,
       EMAIL,
       EMAIL_ADDRESS,
       EMAIL_ADDRESS_FOR_PAYMENT_NOT,
       EMAIL_ADDRESS_FOR_PAYMENT_NO_0,
       EMAIL_FOR_CUSTOMER_STATEMENT,
       EMAIL_FOR_CUSTOMER_STATEMENT_,
       EMAIL_FOR_CUSTOMER_STATEMENT_0,
       EMAIL_FOR_CUSTOMER_STATEMENT_1,
       EMPLOYEE_ID,
       EXPENSE_ACCOUNT_ID,
       FAIR_SIZE,
       FAIR_TYPE_ID,
       FAX,
       FINANCIAL,
       FORWARDERS_ADDRESS_ID,
       FORWARDER_ADDRESS,
       FREIGHT_ESTIMATE_METHOD_ID,
       FREIGHT_RATE,
       FULL_NAME,
       HOME_PHONE,
       INCOTERM,
       IS1099ELIGIBLE,
       ISEMAILHTML,
       ISEMAILPDF,
       ISINACTIVE,
       IS_PERSON,
       LABOR_COST,
       LAST_MODIFIED_DATE,
       LAST_SALES_ACTIVITY,
       LEGACY_CUSTOMER_IDCUSTOM,
       LINE1,
       LINE2,
       LINE3,
       LINE_OF_BUSINESS_ID,
       LINE_OF_BUSINESS,
       LOGINACCESS,
       LSA_LINK,
       LSA_LINK_NAME,
       MOBILE_PHONE,
       MOE_ID,
       NAME,
       NO_OF_CHILDREN_ENROLLED,
       OLD_CUSTOMER_CODE,
       OLD_PARENT_CODE,
       OPENBALANCE,
       OPENBALANCE_FOREIGN,
       OPENING_BALANCE,
       PAYABLES_ACCOUNT_ID,
       PAYMENT_TERMS_ID,
       PHILHEALTH,
       PHONE,
       PRICE_GROUP_ID,
       PRINTONCHECKAS,
       PROJECT_SCOPE_STATEMENT,
       PROVIDENT_FUND_NUMBER,
       PURCHASEORDERAMOUNT,
       PURCHASEORDERQUANTITY,
       PURCHASEORDERQUANTITYDIFF,
       RECEIPTAMOUNT,
       RECEIPTQUANTITY,
       RECEIPTQUANTITYDIFF,
       REGION_ID,
       REWARDS_BAND_ID,
       REWARD_EARNER_ID,
       ROUTE_CODE_ID,
       SALES_TERRITORYDO_NOT_USE_ID,
       SCHEMAI1L_FOR_INVOICE,
       SCHEMAIL_FOR_INVOICE,
       SCHOLASTIC_SALES_TERRITORY_ID,
       SELLING_RIGHTS_ID,
       SHIPADDRESS,
       SHIPPING_PREFERENCE_ID,
       SNIPP_MEMBER_ID,
       SOR_DISCOUNT_ID,
       SOR_DURATION_FROM_DAYS,
       SOR_DURATION_TO_DAYS,
       SOR_TAG,
       SOR_THRESHOLD,
       SPONSOR,
       STAPLES,
       STATE,
       SUBSIDIARY,
       SUBSIDIARY_NAME,
       TAXIDNUM,
       TAX_CONTACT_FIRST_NAME,
       TAX_CONTACT_ID,
       TAX_CONTACT_LAST_NAME,
       TAX_CONTACT_MIDDLE_NAME,
       THIRD_PARTY,
       TIN,
       TOTAL_QUANTITY,
       TRANSACTIONS_NEED_APPROVAL,
       UEN,
       UK_OTC_CODE,
       UNBILLED_ORDERS,
       UNBILLED_ORDERS_FOREIGN,
       URL,
       US_OTC_CODE,
       VAT_REGISTRATION_NO,
       VENDOR_EXTID,
       VENDOR_ID,
       VENDOR_TYPE_ID,
       VENDOR_TYPE,
       ZIPCODE,
       ZONE_NUMBER_ID
FROM dw_prestage.vendors
WHERE EXISTS (SELECT 1
              FROM dw_prestage.vendors_update
              WHERE dw_prestage.vendors_update.vendor_id = dw_prestage.vendors.vendor_id);

COMMIT;

/* dimension ->insert new records in dim vendors */ 
INSERT INTO dw.vendors
(
  VENDOR_ID,
  VENDOR_EXTID,
  NAME,
  EMAIL,
  FULL_NAME,
  BILLADDRESS,
  SHIPADDRESS,
  ACCOUNTNUMBER,
  LINE1,
  LINE2,
  LINE3,
  ZIPCODE,
  CITY,
  STATE,
  COUNTRY,
  COMPANYNAME,
  CURRENCY,
  CURRENCY_ID,
  EFT_BILL_PAYMENT,
  IS1099ELIGIBLE,
  ISINACTIVE,
  TYPE,
  LINE_OF_BUSINESS,
  LINE_OF_BUSINESS_ID,
  SUBSIDIARY_NAME,
  SUBSIDIARY_ID,
  VENDOR_TYPE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT VENDOR_ID,
       NVL(VENDOR_EXTID,'NA_GDW') ,
       NVL(NAME,'NA_GDW') ,
       NVL(EMAIL,'NA_GDW') ,
       NVL(FULL_NAME,'NA_GDW'	) ,
       NVL(BILLADDRESS,'NA_GDW') ,
       NVL(SHIPADDRESS,'NA_GDW') ,
       NVL(ACCOUNTNUMBER,'NA_GDW') ,
       NVL(LINE1,'NA_GDW') ,
       NVL(LINE2,'NA_GDW') ,
       NVL(LINE3,'NA_GDW') ,
       NVL(ZIPCODE,'NA_GDW') ,
       NVL(CITY,'NA_GDW') ,
       NVL(STATE,'NA_GDW') ,
       NVL(COUNTRY,'NA_GDW') ,
       NVL(COMPANYNAME,'NA_GDW') ,
       NVL(CURRENCY_NAME,'NA_GDW') ,
       NVL(CURRENCY_ID,-99),
       NVL(EFT_BILL_PAYMENT,'NA_GDW'),
       NVL(IS1099ELIGIBLE,'NA_GDW'),
       NVL(ISINACTIVE,'NA_GDW'),
       NVL(IS_PERSON,'NA_GDW'),
       NVL(LINE_OF_BUSINESS,'NA_GDW') ,
       NVL(LINE_OF_BUSINESS_ID,-99),
       NVL(SUBSIDIARY_NAME,'NA_GDW') ,
       NVL(SUBSIDIARY,-99),
       NVL(VENDOR_TYPE,'NA_GDW') ,
       sysdate,
       '9999-12-31 23:59:59',
       'A'
FROM dw_prestage.vendors_insert A;

/* dimension -> update old record as part of SCD2 maintenance*/ 
UPDATE dw.vendors
   SET dw_active = 'I',
       DATE_ACTIVE_TO = (sysdate -1)
WHERE dw_active = 'A'
AND   sysdate>= date_active_from
AND   sysdate< date_active_to
AND   EXISTS (SELECT 1
              FROM dw_prestage.vendors_update
              WHERE dw.vendors.vendor_id = dw_prestage.vendors_update.vendor_id
              AND   dw_prestage.vendors_update.ch_type = 2);

/* dimension -> insert the new records as part of SCD2 maintenance*/ 
INSERT INTO dw.vendors
(
  VENDOR_ID,
  VENDOR_EXTID,
  NAME,
  EMAIL,
  FULL_NAME,
  BILLADDRESS,
  SHIPADDRESS,
  ACCOUNTNUMBER,
  LINE1,
  LINE2,
  LINE3,
  ZIPCODE,
  CITY,
  STATE,
  COUNTRY,
  COMPANYNAME,
  CURRENCY,
  CURRENCY_ID,
  EFT_BILL_PAYMENT,
  IS1099ELIGIBLE,
  ISINACTIVE,
  TYPE,
  LINE_OF_BUSINESS,
  LINE_OF_BUSINESS_ID,
  SUBSIDIARY_NAME,
  SUBSIDIARY_ID,
  VENDOR_TYPE,
  DATE_ACTIVE_FROM,
  DATE_ACTIVE_TO,
  DW_ACTIVE
)
SELECT VENDOR_ID,
       NVL(VENDOR_EXTID,'NA_GDW') ,
       NVL(NAME,'NA_GDW') ,
       NVL(EMAIL,'NA_GDW') ,
       NVL(FULL_NAME,'NA_GDW'	) ,
       NVL(BILLADDRESS,'NA_GDW') ,
       NVL(SHIPADDRESS,'NA_GDW') ,
       NVL(ACCOUNTNUMBER,'NA_GDW') ,
       NVL(LINE1,'NA_GDW') ,
       NVL(LINE2,'NA_GDW') ,
       NVL(LINE3,'NA_GDW') ,
       NVL(ZIPCODE,'NA_GDW') ,
       NVL(CITY,'NA_GDW') ,
       NVL(STATE,'NA_GDW') ,
       NVL(COUNTRY,'NA_GDW') ,
       NVL(COMPANYNAME,'NA_GDW') ,
       NVL(CURRENCY_NAME,'NA_GDW') ,
       NVL(CURRENCY_ID,-99),
       NVL(EFT_BILL_PAYMENT,'NA_GDW'),
       NVL(IS1099ELIGIBLE,'NA_GDW'),
       NVL(ISINACTIVE,'NA_GDW'),
       NVL(IS_PERSON,'NA_GDW'),
       NVL(LINE_OF_BUSINESS,'NA_GDW') ,
       NVL(LINE_OF_BUSINESS_ID,-99),
       NVL(SUBSIDIARY_NAME,'NA_GDW') ,
       NVL(SUBSIDIARY,-99),
       NVL(VENDOR_TYPE,'NA_GDW') ,
       sysdate,
       '9999-12-31 23:59:59',
       'A'
FROM dw_prestage.vendors A
WHERE EXISTS (SELECT 1
              FROM dw_prestage.vendors_update
              WHERE a.vendor_id = dw_prestage.vendors_update.vendor_id
              AND   dw_prestage.vendors_update.ch_type = 2);

/* dimension -> update records as part of SCD1 maintenance */ 
UPDATE dw.vendors
   SET VENDOR_EXTID = NVL(dw_prestage.vendors.VENDOR_EXTID,'NA_GDW'),
       NAME = NVL(dw_prestage.vendors.NAME,'NA_GDW'),
       EMAIL = NVL(dw_prestage.vendors.EMAIL,'NA_GDW'),
       FULL_NAME = NVL(dw_prestage.vendors.FULL_NAME,'NA_GDW'),
       EFT_BILL_PAYMENT = NVL(dw_prestage.vendors.EFT_BILL_PAYMENT,'NA_GDW'),
       IS1099ELIGIBLE = NVL(dw_prestage.vendors.IS1099ELIGIBLE,'NA_GDW'),
       ISINACTIVE = NVL(dw_prestage.vendors.ISINACTIVE,'NA_GDW'),
       TYPE = NVL(dw_prestage.vendors.IS_PERSON,'NA_GDW'),
       LINE_OF_BUSINESS = NVL(dw_prestage.vendors.LINE_OF_BUSINESS,'NA_GDW'),
       LINE_OF_BUSINESS_ID = NVL(dw_prestage.vendors.LINE_OF_BUSINESS_ID,-99),
       SUBSIDIARY_NAME = NVL(dw_prestage.vendors.SUBSIDIARY_NAME,'NA_GDW'),
       SUBSIDIARY_ID = NVL(dw_prestage.vendors.SUBSIDIARY,-99),
       VENDOR_TYPE = NVL(dw_prestage.vendors.VENDOR_TYPE,'NA_GDW')
FROM dw_prestage.vendors
WHERE dw.vendors.vendor_id = dw_prestage.vendors.vendor_id
AND   EXISTS (SELECT 1
              FROM dw_prestage.vendors_update
              WHERE dw_prestage.vendors.vendor_id = dw_prestage.vendors_update.vendor_id
              AND   dw_prestage.vendors_update.ch_type = 1);

/* dimension -> logically delete dw records */ 
UPDATE dw.vendors
   SET DATE_ACTIVE_TO = sysdate -1,
       dw_active = 'I'
FROM dw_prestage.vendors_delete
WHERE dw.vendors.vendor_id = dw_prestage.vendors_delete.vendor_id;

COMMIT;

